// Mock Data Service - Realistic seed data for the entire dashboard

// User Profile
export const mockUser = {
  id: 1,
  name: 'Alex Johnson',
  email: 'alex.johnson@example.com',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
  role: 'Product Manager',
  joinDate: '2024-01-15',
  settings: {
    theme: 'dark',
    notifications: true,
    language: 'English',
    timezone: 'UTC-8',
  }
};

// Tasks Data
export const mockTasks = [
  {
    id: 1,
    title: 'Design new landing page',
    description: 'Create mockups for the new product landing page with modern design',
    status: 'in-progress',
    priority: 'high',
    dueDate: '2024-11-20',
    category: 'Design',
    tags: ['UI/UX', 'Marketing'],
    assignee: 'Alex Johnson',
    progress: 65,
    createdAt: '2024-11-10',
  },
  {
    id: 2,
    title: 'Fix authentication bug',
    description: 'Users are experiencing issues with password reset flow',
    status: 'todo',
    priority: 'urgent',
    dueDate: '2024-11-16',
    category: 'Development',
    tags: ['Bug', 'Backend'],
    assignee: 'Sarah Chen',
    progress: 0,
    createdAt: '2024-11-14',
  },
  {
    id: 3,
    title: 'Update documentation',
    description: 'Add API documentation for new endpoints',
    status: 'completed',
    priority: 'medium',
    dueDate: '2024-11-12',
    category: 'Documentation',
    tags: ['API', 'Docs'],
    assignee: 'Mike Wilson',
    progress: 100,
    createdAt: '2024-11-08',
  },
  {
    id: 4,
    title: 'Conduct user interviews',
    description: 'Interview 10 users about the new feature',
    status: 'in-progress',
    priority: 'high',
    dueDate: '2024-11-25',
    category: 'Research',
    tags: ['User Research', 'UX'],
    assignee: 'Emily Davis',
    progress: 40,
    createdAt: '2024-11-11',
  },
  {
    id: 5,
    title: 'Optimize database queries',
    description: 'Improve performance of slow queries in production',
    status: 'todo',
    priority: 'medium',
    dueDate: '2024-11-22',
    category: 'Development',
    tags: ['Performance', 'Backend'],
    assignee: 'Alex Johnson',
    progress: 0,
    createdAt: '2024-11-13',
  },
  {
    id: 6,
    title: 'Create marketing materials',
    description: 'Design social media posts for product launch',
    status: 'todo',
    priority: 'low',
    dueDate: '2024-11-30',
    category: 'Marketing',
    tags: ['Social Media', 'Design'],
    assignee: 'Lisa Brown',
    progress: 0,
    createdAt: '2024-11-14',
  },
];

// Activities Data
export const mockActivities = [
  {
    id: 1,
    title: 'Team Standup',
    type: 'meeting',
    date: '2024-11-15',
    time: '09:00',
    duration: 30,
    location: 'Zoom',
    attendees: ['Alex Johnson', 'Sarah Chen', 'Mike Wilson'],
    description: 'Daily team sync to discuss progress and blockers',
    status: 'upcoming',
    color: '#10b981',
  },
  {
    id: 2,
    title: 'Client Presentation',
    type: 'meeting',
    date: '2024-11-15',
    time: '14:00',
    duration: 60,
    location: 'Conference Room A',
    attendees: ['Alex Johnson', 'Emily Davis', 'Client Team'],
    description: 'Present Q4 results and roadmap',
    status: 'upcoming',
    color: '#3b82f6',
  },
  {
    id: 3,
    title: 'Code Review Session',
    type: 'work',
    date: '2024-11-15',
    time: '11:00',
    duration: 45,
    location: 'Online',
    attendees: ['Sarah Chen', 'Mike Wilson'],
    description: 'Review PRs for authentication feature',
    status: 'upcoming',
    color: '#8b5cf6',
  },
  {
    id: 4,
    title: 'Lunch Break',
    type: 'personal',
    date: '2024-11-15',
    time: '12:00',
    duration: 60,
    location: 'Cafeteria',
    attendees: ['Alex Johnson'],
    description: 'Lunch with team',
    status: 'upcoming',
    color: '#f59e0b',
  },
  {
    id: 5,
    title: 'Design Workshop',
    type: 'meeting',
    date: '2024-11-16',
    time: '10:00',
    duration: 120,
    location: 'Design Studio',
    attendees: ['Alex Johnson', 'Emily Davis', 'Lisa Brown'],
    description: 'Brainstorm new feature designs',
    status: 'upcoming',
    color: '#ec4899',
  },
  {
    id: 6,
    title: 'Sprint Planning',
    type: 'meeting',
    date: '2024-11-18',
    time: '09:00',
    duration: 90,
    location: 'Conference Room B',
    attendees: ['Entire Team'],
    description: 'Plan next sprint tasks and goals',
    status: 'upcoming',
    color: '#10b981',
  },
];

// Community Posts Data
export const mockPosts = [
  {
    id: 1,
    author: {
      name: 'Sarah Chen',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
      role: 'Senior Developer',
    },
    content: 'Just shipped the new authentication system! 🚀 The password reset flow is now live. Let me know if you encounter any issues.',
    timestamp: '2 hours ago',
    likes: 24,
    comments: 8,
    shares: 3,
    liked: false,
    tags: ['Development', 'Launch'],
  },
  {
    id: 2,
    author: {
      name: 'Mike Wilson',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
      role: 'Tech Lead',
    },
    content: 'Great team meeting today! Excited about the roadmap for Q1 2025. We have some amazing features coming up. 💪',
    timestamp: '5 hours ago',
    likes: 42,
    comments: 12,
    shares: 5,
    liked: true,
    tags: ['Team', 'Planning'],
  },
  {
    id: 3,
    author: {
      name: 'Emily Davis',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
      role: 'UX Designer',
    },
    content: 'Check out the new design system I\'ve been working on! Would love to get your feedback. Link in comments 👇',
    timestamp: '1 day ago',
    likes: 67,
    comments: 23,
    shares: 15,
    liked: true,
    tags: ['Design', 'Feedback'],
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800',
  },
  {
    id: 4,
    author: {
      name: 'Lisa Brown',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
      role: 'Marketing Manager',
    },
    content: 'Our latest blog post just hit 10k views! 🎉 Thanks everyone for sharing. Keep the momentum going!',
    timestamp: '2 days ago',
    likes: 89,
    comments: 31,
    shares: 42,
    liked: false,
    tags: ['Marketing', 'Milestone'],
  },
  {
    id: 5,
    author: {
      name: 'Alex Johnson',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
      role: 'Product Manager',
    },
    content: 'Reminder: Sprint review tomorrow at 2 PM. Please have your demos ready. Looking forward to seeing what everyone built! 🎯',
    timestamp: '3 days ago',
    likes: 34,
    comments: 7,
    shares: 2,
    liked: false,
    tags: ['Team', 'Sprint'],
  },
];

// Messages Data
export const mockConversations = [
  {
    id: 1,
    user: {
      name: 'Sarah Chen',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
      status: 'online',
    },
    lastMessage: 'Sounds good! Let me know when you\'re ready.',
    timestamp: '2m ago',
    unread: 2,
    messages: [
      {
        id: 1,
        sender: 'Sarah Chen',
        content: 'Hey! Did you get a chance to review the PR?',
        timestamp: '10:30 AM',
        read: true,
      },
      {
        id: 2,
        sender: 'me',
        content: 'Yes! Looks great. Just left a few minor comments.',
        timestamp: '10:32 AM',
        read: true,
      },
      {
        id: 3,
        sender: 'Sarah Chen',
        content: 'Perfect! I\'ll address those now.',
        timestamp: '10:33 AM',
        read: true,
      },
      {
        id: 4,
        sender: 'me',
        content: 'Great! Want to do a quick call to discuss the architecture?',
        timestamp: '10:35 AM',
        read: true,
      },
      {
        id: 5,
        sender: 'Sarah Chen',
        content: 'Sounds good! Let me know when you\'re ready.',
        timestamp: '10:36 AM',
        read: false,
      },
    ],
  },
  {
    id: 2,
    user: {
      name: 'Mike Wilson',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
      status: 'away',
    },
    lastMessage: 'Thanks! I\'ll check it out.',
    timestamp: '1h ago',
    unread: 0,
    messages: [
      {
        id: 1,
        sender: 'me',
        content: 'Hey Mike, I updated the documentation.',
        timestamp: '9:15 AM',
        read: true,
      },
      {
        id: 2,
        sender: 'Mike Wilson',
        content: 'Thanks! I\'ll check it out.',
        timestamp: '9:20 AM',
        read: true,
      },
    ],
  },
  {
    id: 3,
    user: {
      name: 'Emily Davis',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
      status: 'online',
    },
    lastMessage: 'Love the new designs! 🎨',
    timestamp: '3h ago',
    unread: 1,
    messages: [
      {
        id: 1,
        sender: 'Emily Davis',
        content: 'Love the new designs! 🎨',
        timestamp: '8:45 AM',
        read: false,
      },
    ],
  },
  {
    id: 4,
    user: {
      name: 'Lisa Brown',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
      status: 'offline',
    },
    lastMessage: 'See you at the meeting!',
    timestamp: '1d ago',
    unread: 0,
    messages: [
      {
        id: 1,
        sender: 'Lisa Brown',
        content: 'See you at the meeting!',
        timestamp: 'Yesterday',
        read: true,
      },
    ],
  },
];

// Analytics Data
export const mockAnalytics = {
  overview: {
    totalTasks: 156,
    completedTasks: 98,
    inProgress: 42,
    overdue: 16,
    completionRate: 62.8,
    avgCompletionTime: 4.2, // days
  },
  tasksByStatus: [
    { status: 'Completed', count: 98, color: '#10b981' },
    { status: 'In Progress', count: 42, color: '#3b82f6' },
    { status: 'Todo', count: 32, color: '#f59e0b' },
    { status: 'Overdue', count: 16, color: '#ef4444' },
  ],
  tasksByPriority: [
    { priority: 'Urgent', count: 24, color: '#ef4444' },
    { priority: 'High', count: 58, color: '#f59e0b' },
    { priority: 'Medium', count: 52, color: '#3b82f6' },
    { priority: 'Low', count: 22, color: '#6b7280' },
  ],
  tasksByCategory: [
    { category: 'Development', count: 64, color: '#3b82f6' },
    { category: 'Design', count: 38, color: '#ec4899' },
    { category: 'Marketing', count: 28, color: '#f59e0b' },
    { category: 'Research', count: 16, color: '#8b5cf6' },
    { category: 'Documentation', count: 10, color: '#10b981' },
  ],
  weeklyProgress: [
    { week: 'Week 1', completed: 12, created: 15 },
    { week: 'Week 2', completed: 18, created: 12 },
    { week: 'Week 3', completed: 15, created: 20 },
    { week: 'Week 4', completed: 22, created: 18 },
  ],
  teamPerformance: [
    { name: 'Alex Johnson', completed: 28, inProgress: 8, rating: 4.8 },
    { name: 'Sarah Chen', completed: 32, inProgress: 6, rating: 4.9 },
    { name: 'Mike Wilson', completed: 24, inProgress: 10, rating: 4.7 },
    { name: 'Emily Davis', completed: 20, inProgress: 12, rating: 4.6 },
    { name: 'Lisa Brown', completed: 18, inProgress: 6, rating: 4.5 },
  ],
};

// Dashboard Stats
export const mockDashboardStats = {
  totalTasks: 156,
  completedToday: 8,
  inProgress: 42,
  upcomingMeetings: 6,
  unreadMessages: 12,
  teamMembers: 24,
  activeProjects: 8,
  completionRate: 62.8,
};

// Recent Activity Feed
export const mockRecentActivity = [
  {
    id: 1,
    type: 'task_completed',
    user: 'Sarah Chen',
    action: 'completed',
    target: 'Fix authentication bug',
    timestamp: '5 minutes ago',
    icon: 'check',
    color: '#10b981',
  },
  {
    id: 2,
    type: 'task_created',
    user: 'Alex Johnson',
    action: 'created',
    target: 'Design new landing page',
    timestamp: '1 hour ago',
    icon: 'plus',
    color: '#3b82f6',
  },
  {
    id: 3,
    type: 'comment',
    user: 'Mike Wilson',
    action: 'commented on',
    target: 'Update documentation',
    timestamp: '2 hours ago',
    icon: 'message',
    color: '#8b5cf6',
  },
  {
    id: 4,
    type: 'task_assigned',
    user: 'Emily Davis',
    action: 'assigned',
    target: 'Conduct user interviews',
    timestamp: '3 hours ago',
    icon: 'user',
    color: '#f59e0b',
  },
  {
    id: 5,
    type: 'meeting',
    user: 'Lisa Brown',
    action: 'scheduled',
    target: 'Team Standup',
    timestamp: '5 hours ago',
    icon: 'calendar',
    color: '#ec4899',
  },
];

// Notifications
export const mockNotifications = [
  {
    id: 1,
    type: 'task',
    title: 'Task deadline approaching',
    message: 'Fix authentication bug is due tomorrow',
    timestamp: '10 minutes ago',
    read: false,
    icon: 'alert',
    color: '#ef4444',
  },
  {
    id: 2,
    type: 'message',
    title: 'New message from Sarah Chen',
    message: 'Sounds good! Let me know when you\'re ready.',
    timestamp: '2 minutes ago',
    read: false,
    icon: 'message',
    color: '#3b82f6',
  },
  {
    id: 3,
    type: 'mention',
    title: 'Mike Wilson mentioned you',
    message: 'In the comment on "Update documentation"',
    timestamp: '1 hour ago',
    read: true,
    icon: 'at',
    color: '#8b5cf6',
  },
  {
    id: 4,
    type: 'meeting',
    title: 'Meeting reminder',
    message: 'Team Standup starts in 30 minutes',
    timestamp: '30 minutes ago',
    read: false,
    icon: 'calendar',
    color: '#10b981',
  },
];

// Export all mock data
export default {
  user: mockUser,
  tasks: mockTasks,
  activities: mockActivities,
  posts: mockPosts,
  conversations: mockConversations,
  analytics: mockAnalytics,
  dashboardStats: mockDashboardStats,
  recentActivity: mockRecentActivity,
  notifications: mockNotifications,
};
